let BITBOX = require('bitbox-sdk').BITBOX;
let bitbox = new BITBOX();
const Address = require("bitbox-sdk").Address
let address = new Address()
console.log(address);
const BitcoinCash = require("bitbox-sdk").BitcoinCash
let bitcoincash = new BitcoinCash()
//const BitDB = require("bitbox-sdk").BitDB
// let bitdb = new BitDB
const Block = require("bitbox-sdk").Block
let block = new Block()
const Blockchain = require("bitbox-sdk").Blockchain
let blockchain = new Blockchain
const CashAccounts = require("bitbox-sdk").CashAccounts
let cashAccounts = new CashAccounts()
const Control = require("bitbox-sdk").Control
let control = new Control()
const Crypto = require("bitbox-sdk").Crypto
let crypto = new Crypto()
const ECPair = require("bitbox-sdk").ECPair
let ecpair = new ECPair()
const Generating = require("bitbox-sdk").Generating
let generating = new Generating()
const HDNode = require("bitbox-sdk").HDNode
let hdnode = new HDNode()
const Mining = require("bitbox-sdk").Mining
let mining = new Mining()
const Mnemonic = require("bitbox-sdk").Mnemonic
let mnemonic = new Mnemonic()
const Price = require("bitbox-sdk").Price
let price = new Price()
const RawTransactions = require("bitbox-sdk").RawTransactions
let rawtransactions = new RawTransactions()
const Schnorr = require("bitbox-sdk").Schnorr
let schnorr = new Schnorr
const Script = require("bitbox-sdk").Script
let script = new Script()
const Socket = require("bitbox-sdk").Socket
let socket = new Socket()
const Transaction = require("bitbox-sdk").Transaction
let transaction = new Transaction
const TransactionBuilder = require("bitbox-sdk").TransactionBuilder
let transactionbuilder = new TransactionBuilder()
const Util = require("bitbox-sdk").Util
let util = new Util()

console.log(bitbox.Address.toLegacyAddress('qzm47qz5ue99y9yl4aca7jnz7dwgdenl85jkfx3znl'));